name: Build

on:
  pull_request:
    branches:
      - main
      - next

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          check-latest: true

      - name: Run Build
        run: |
          npm ci
          npm test
          npm run build
