name: Pre-Release

env:
  NPM_PRE_RELEASE: 'true'

on:
  push:
    branches:
      - next

jobs:
  prerelease:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          check-latest: true

      - name: Run Build
        run: |
          npm ci
          npm test
          npm run build

      # Docs: https://github.com/codfish/semantic-release-action#readme
      - name: Publish NPM Package
        id: package
        uses: codfish/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NODE_AUTH_TOKEN: ${{ secrets.GH_PAT }}
